// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stnwvookqxwhzkirgtkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0bnd2b29rcXh3aHpraXJndGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTI1NjMsImV4cCI6MjA3MjU4ODU2M30.Of8Zbfbiji4vj2-EuhTwERZUhQT9XgjuEhsG1MNimH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});