// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbpmdmmmastkznaggevx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZicG1kbW1tYXN0a3puYWdnZXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNjQ4OTgsImV4cCI6MjA2OTk0MDg5OH0.7TzMP0A5O1ws4VKQL_XN6Y5MwMLb5GqQ2unXNpaSUaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});